name: Testar Compilação do PPL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Instalar compiladores
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang

    - name: Compilar com Clang++
      run: |
        clang++ -O3 -std=c++17 src/ppl.cpp -o ppl_clang

    - name: Compilar com G++
      run: |
        g++ -O3 -std=c++17 src/ppl.cpp -o ppl_g++
