name: Release Windows Executable

on:
  push:
    branches: [ main ]
    paths:
      # roda SÓ quando houver alteração neste arquivo específico
      - 'src/ppl.cpp'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: baixar o código
        uses: actions/checkout@v4

      - name: compilar c++ no windows (g++)
        shell: powershell
        run: |
          mkdir build -ErrorAction SilentlyContinue
          g++ -O3 -std=c++17 src/ppl.cpp -o build/ppl.exe

      - name: criar / atualizar release fixa no github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "PPL Builds (Latest)"
          body: "compilação automática de alta performance para windows gerada a partir das últimas alterações no `ppl.cpp`."
          draft: false
          prerelease: false
          files: build/ppl.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
